#!/bin/bash
do_run=1 # Execute(evaluate) the commands
#do_run=0 # Don't evaluate any commands
#
echo ""
echo "Setup Python!"
echo ""
#!/bin/bash
do_run=1 # Execute(evaluate) the commands
#do_run=0 # Don't evaluate any commands
#
echo ""
echo "Setting up JQ"
echo ""

mkdir -p ~/bin
cd ~/bin

curl -LJO http://thedrop.sap-partner-eng.com/files/python3.7.3
chmod 755 python3.7.3
ln -s python3.7.3 python3


#mkdir -p ~/lib
#cd ~/lib

echo "" >> ~/.bashrc
echo "export PYTHONHOME=/home/user" >> ~/.bashrc


