#!/bin/bash
do_run=1 # Execute(evaluate) the commands
#do_run=0 # Don't evaluate any commands
#
echo ""
echo "Setting up JQ"
echo ""

mkdir -p ~/bin
cd ~/bin

curl -LJO http://thedrop.sap-partner-eng.com/files/jq
chmod 755 jq
mkdir -p ~/lib
cd ~/lib

curl -LJO http://thedrop.sap-partner-eng.com/files/libjq.so.1.0.4
curl -LJO http://thedrop.sap-partner-eng.com/files/libjq.so.1.0.4
curl -LJO http://thedrop.sap-partner-eng.com/files/libonig.so.5.0.0
ln -s libjq.so.1.0.4 libjq.so.1
ln -s libjq.so.1.0.4 libjq.so
ln -s libonig.so.5.0.0 libonig.so.5
ln -s libonig.so.5.0.0 libonig.so

echo "" >> ~/.bashrc
echo "export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/home/user/lib" >> ~/.bashrc
echo "" >> ~/.bashrc
echo "export PATH=$PATH:/home/user/bin" >> ~/.bashrc

echo "Stop your Dev Space and Start it again."

