#!/bin/bash
do_run=1 # Execute(evaluate) the commands
#do_run=0 # Don't evaluate any commands
#
echo ""
echo "Do Something!"
echo ""
curl -o Python-3.8.3.tgz https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz
tar xzvf Python-3.8.3.tgz
cd Python-3.8.3
mkdir -p /home/user/default-plugins
cd /home/user/default-plugins
curl -o ms-python.python-2020.8.106424.vsix http://thedrop.sap-partner-eng.com/files/ms-python.python-2020.8.106424.vsix
cd ~
echo ""
echo "Restart this workspace!"
echo ""
