#!/bin/bash
do_run=1 # Execute(evaluate) the commands
#do_run=0 # Don't evaluate any commands
#
echo ""
echo "Do Something!"
echo ""
mkdir -p /home/user/default-plugins
cd /home/user/default-plugins
curl -o mtxr.sqltools-0.23.0.vsix http://thedrop.sap-partner-eng.com/files/mtxr.sqltools-0.23.0.vsix
curl -o SAPOSS.sap-hana-driver-for-sqltools-0.2.1.vsix http://thedrop.sap-partner-eng.com/files/SAPOSS.sap-hana-driver-for-sqltools-0.2.1.vsix
cd ~
echo ""
echo "STOP this workspace and then START it again!"
echo ""
